#!/bin/sh

NAME="$1"
PWD="$(pwd)"
case "$(basename "$PWD")" in
	libmcb) ;;
	tools) PWD="$(dirname "$PWD")" ;;
	*)
		echo "Please run this script in 'libmcb' or 'tools' directory"
		exit 1
		;;
esac

NAME_UPPER="$(echo "$NAME" | tr '[:lower:]' '[:upper:]')"
cat > "include/mcb/inst/$NAME.h" << EOF
/* This file is part of libmcb.
   SPDX-License-Identifier: LGPL-3.0-or-later
*/
#ifndef LIBMCB_INST_${NAME_UPPER}_H
#define LIBMCB_INST_${NAME_UPPER}_H

#endif
EOF

cat > "src/inst/$NAME.c" << EOF
/* This file is part of libmcb.
   SPDX-License-Identifier: LGPL-3.0-or-later
*/
#include "mcb/inst/${NAME}.h"

EOF
